language: c

compiler:
  - clang
  - gcc

before_install: sudo apt-get update

install: sudo apt-get install libasound2-dev libgtk-3-dev libnotify-dev intltool

script:
  - ./autogen.sh --enable-debug
  - make
